default: &default
  adapter: mysql2
  encoding: utf8
  charset: utf8
  collation: utf8_general_ci 
  pool: 5
  username: root
  password:
  host: localhost

test:
  <<: *default
  database: test
  username: <%= ENV['DB_USERNAME'] || 'root' %>
  password: <%= ENV['DB_PASSWORD'] || '' %>
  host: <%= ENV['DB_HOST'] || '127.0.0.1' %>
  socket: /tmp/mysql.sock
  
development:
  <<: *default
  database: db/development

production:
  <<: *default
  database: db/production